#!/bin/bash

COUNT=$1
FILE_NAME=$2
POSTFIX=$3

echo Creating $COUNT files with name $FILE_NAME ending with $POSTFIX

COUNTER=0
while [  $COUNTER -lt $COUNT ]; do
    OUTPUT=${FILE_NAME}_${COUNTER}.${POSTFIX}
    touch $OUTPUT
    echo "Lorem ipsum dolor sit amet," >> $OUTPUT
    echo "consetetur sadipscing elitr," >> $OUTPUT
    echo "sed diam nonumy eirmod tempor" >> $OUTPUT
    echo "invidunt ut labore et dolore" >> $OUTPUT
    echo "magna aliquyam erat, sed diam voluptua." >> $OUTPUT
    echo $COUNTER >> $OUTPUT
    let COUNTER=COUNTER+1
done
